name: Test

inputs:
  python_version:
    description: Python version, e.g. '3.10'
    type: string
    default: '3.10'
  poetry_version:
    description: Poetry version, e.g. '1.3.1'
    type: string
    default: '1.3.1'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry_version }}
        virtualenvs-in-project: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox==3.25.0 poetry tox-poetry tox-gh-actions

    - name: Test with tox
      run: |
        rm -rf ./.tox | true
        tox
