name: Test

inputs:
  python_version:
    description: Python version, e.g. '3.10'
    type: string
    default: '3.10'
  poetry_version:
    description: Poetry version, e.g. '1.3.1'
    type: string
    default: '1.3.1'
  deploy_target:
    required: true
    type: string
    description: "Deploy Target"
  app_slug:
    description: Application slug in kebab case, e.g. 'demo'
    type: string
    required: true
runs:
  using: composite
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ inputs.poetry_version }}
          virtualenvs-in-project: true

      - name: Install dependencies
        shell: bash
        run: make install

      - name: Run migrations up command
        shell: bash
        run: |
          alembic upgrade head